"""create table

Revision ID: bd8162c8732b
Revises: c90d73cc9a95
Create Date: 2024-07-28 20:08:32.853700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8162c8732b'
down_revision: Union[str, None] = 'c90d73cc9a95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_model', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('llm_model', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_model', 'updated_at')
    op.drop_column('llm_model', 'created_at')
    # ### end Alembic commands ###
