"""create table

Revision ID: 0a1ccc3fc5d2
Revises: ddf5b28fa97a
Create Date: 2024-08-14 23:14:22.742272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a1ccc3fc5d2'
down_revision: Union[str, None] = 'ddf5b28fa97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('model', sa.String(), nullable=True))
    op.drop_column('api_key', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('api_key', 'model')
    # ### end Alembic commands ###
