"""create table

Revision ID: b42be8abd51e
Revises: ec812d50f68a
Create Date: 2024-09-12 17:36:32.828251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42be8abd51e'
down_revision: Union[str, None] = 'ec812d50f68a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poll', 'order')
    # ### end Alembic commands ###
