"""create table

Revision ID: c90d73cc9a95
Revises: 
Create Date: 2024-07-28 10:57:59.723293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c90d73cc9a95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('instance', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('properties', sa.String(), nullable=True),
    sa.Column('server_ip', sa.String(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.Column('max_request_num', sa.Integer(), nullable=True),
    sa.Column('gpu', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_model')
    # ### end Alembic commands ###
