"""create table

Revision ID: 21745bc0a22a
Revises: 8d9e38623928
Create Date: 2024-08-23 17:45:08.484967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21745bc0a22a'
down_revision: Union[str, None] = '8d9e38623928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_key', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('instance', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_instance_api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_instance_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ),
    sa.ForeignKeyConstraint(['model_instance_id'], ['model_instance.id'], ),
    sa.PrimaryKeyConstraint('id', 'model_instance_id', 'api_key_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_instance_api_key')
    op.drop_table('model_instance')
    # ### end Alembic commands ###
